import React from "react";
import Products from "containers/Products";
import { ProductsApi } from "types/api";

const App = () => {
    const products: ProductsApi = [
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "1",
            name: "Shirt 1",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
        {
            id: "2",
            name: "Shirt 2",
            type: "shirts",
            color: ["Black"],
            manufacturer: "HM",
            price: 100,
        },
    ];

    return (
        <div className="App">
            <Products products={products} />
        </div>
    );
};

export default App;
